
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed Window;
	
	private global::Gtk.ComboBox FromCurrency;
	
	private global::Gtk.ComboBox ToCurrency;
	
	private global::Gtk.Image ToArrow;
	
	private global::Gtk.Image ToForbidden;
	
	private global::Gtk.Frame MainFrame;
	
	private global::Gtk.Fixed FrameField;
	
	private global::Gtk.Entry FromInputLabel;
	
	private global::Gtk.Label FromInput;
	
	private global::Gtk.Image FromInputError;
	
	private global::Gtk.Entry ToInputLabel;
	
	private global::Gtk.Label ToInput;
	
	private global::Gtk.Button ConvertButton;
	
	private global::Gtk.Image ConvertButtonIcon;
	
	private global::Gtk.Label Frame;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 400;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Конвертер валют");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icons/dollar-icon.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.Window = new global::Gtk.Fixed ();
		this.Window.HeightRequest = 100;
		this.Window.Name = "Window";
		this.Window.HasWindow = false;
		// Container child Window.Gtk.Fixed+FixedChild
		this.FromCurrency = global::Gtk.ComboBox.NewText ();
		this.FromCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Рубли"));
		this.FromCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Евро"));
		this.FromCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Доллары"));
		this.FromCurrency.WidthRequest = 300;
		this.FromCurrency.Name = "FromCurrency";
		this.FromCurrency.Active = 0;
		this.Window.Add (this.FromCurrency);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.Window [this.FromCurrency]));
		w1.X = 50;
		w1.Y = 50;
		// Container child Window.Gtk.Fixed+FixedChild
		this.ToCurrency = global::Gtk.ComboBox.NewText ();
		this.ToCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Рубли"));
		this.ToCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Евро"));
		this.ToCurrency.AppendText (global::Mono.Unix.Catalog.GetString ("Доллары"));
		this.ToCurrency.WidthRequest = 300;
		this.ToCurrency.Name = "ToCurrency";
		this.ToCurrency.Active = 1;
		this.Window.Add (this.ToCurrency);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.Window [this.ToCurrency]));
		w2.X = 450;
		w2.Y = 50;
		// Container child Window.Gtk.Fixed+FixedChild
		this.ToArrow = new global::Gtk.Image ();
		this.ToArrow.Name = "ToArrow";
		this.ToArrow.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icons/arrow-right.png"));
		this.Window.Add (this.ToArrow);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.Window [this.ToArrow]));
		w3.X = 375;
		w3.Y = 45;
		// Container child Window.Gtk.Fixed+FixedChild
		this.ToForbidden = new global::Gtk.Image ();
		this.ToForbidden.Name = "ToForbidden";
		this.ToForbidden.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icons/forbidden.png"));
		this.Window.Add (this.ToForbidden);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.Window [this.ToForbidden]));
		w4.X = 375;
		w4.Y = 45;
		// Container child Window.Gtk.Fixed+FixedChild
		this.MainFrame = new global::Gtk.Frame ();
		this.MainFrame.WidthRequest = 780;
		this.MainFrame.HeightRequest = 250;
		this.MainFrame.Name = "MainFrame";
		this.MainFrame.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child MainFrame.Gtk.Container+ContainerChild
		this.FrameField = new global::Gtk.Fixed ();
		this.FrameField.HeightRequest = 100;
		this.FrameField.Name = "FrameField";
		this.FrameField.HasWindow = false;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.FromInputLabel = new global::Gtk.Entry ();
		this.FromInputLabel.WidthRequest = 250;
		this.FromInputLabel.CanFocus = true;
		this.FromInputLabel.Name = "FromInputLabel";
		this.FromInputLabel.IsEditable = true;
		this.FromInputLabel.InvisibleChar = '●';
		this.FrameField.Add (this.FromInputLabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.FromInputLabel]));
		w5.X = 50;
		w5.Y = 50;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.FromInput = new global::Gtk.Label ();
		this.FromInput.Name = "FromInput";
		this.FromInput.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Исходная сумма</b>");
		this.FromInput.UseMarkup = true;
		this.FrameField.Add (this.FromInput);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.FromInput]));
		w6.X = 50;
		w6.Y = 20;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.FromInputError = new global::Gtk.Image ();
		this.FromInputError.Name = "FromInputError";
		this.FromInputError.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icons/forbiddenInput.png"));
		this.FrameField.Add (this.FromInputError);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.FromInputError]));
		w7.X = 305;
		w7.Y = 55;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.ToInputLabel = new global::Gtk.Entry ();
		this.ToInputLabel.WidthRequest = 250;
		this.ToInputLabel.CanFocus = true;
		this.ToInputLabel.Name = "ToInputLabel";
		this.ToInputLabel.IsEditable = false;
		this.ToInputLabel.InvisibleChar = '●';
		this.FrameField.Add (this.ToInputLabel);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.ToInputLabel]));
		w8.X = 450;
		w8.Y = 50;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.ToInput = new global::Gtk.Label ();
		this.ToInput.Name = "ToInput";
		this.ToInput.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Конечная сумма</b>");
		this.ToInput.UseMarkup = true;
		this.FrameField.Add (this.ToInput);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.ToInput]));
		w9.X = 450;
		w9.Y = 20;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.ConvertButton = new global::Gtk.Button ();
		this.ConvertButton.WidthRequest = 300;
		this.ConvertButton.HeightRequest = 80;
		this.ConvertButton.CanFocus = true;
		this.ConvertButton.Name = "ConvertButton";
		this.ConvertButton.UseUnderline = true;
		this.ConvertButton.FocusOnClick = false;
		this.ConvertButton.Label = "Конвертировать";
		this.FrameField.Add (this.ConvertButton);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.ConvertButton]));
		w10.X = 230;
		w10.Y = 110;
		// Container child FrameField.Gtk.Fixed+FixedChild
		this.ConvertButtonIcon = new global::Gtk.Image ();
		this.ConvertButtonIcon.Name = "ConvertButtonIcon";
		this.ConvertButtonIcon.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icons/icon_convert.png"));
		this.FrameField.Add (this.ConvertButtonIcon);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.FrameField [this.ConvertButtonIcon]));
		w11.X = 255;
		w11.Y = 125;
		this.MainFrame.Add (this.FrameField);
		this.Frame = new global::Gtk.Label ();
		this.Frame.Name = "Frame";
		this.Frame.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Калькулятор валют</b>");
		this.Frame.UseMarkup = true;
		this.MainFrame.LabelWidget = this.Frame;
		this.Window.Add (this.MainFrame);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.Window [this.MainFrame]));
		w13.X = 10;
		w13.Y = 120;
		this.Add (this.Window);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.ToForbidden.Hide ();
		this.FromInputError.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.FromCurrency.Changed += new global::System.EventHandler (this.OnFromCurrencyChanged);
		this.ToCurrency.Changed += new global::System.EventHandler (this.OnToCurrencyChanged);
		this.FromInputLabel.Changed += new global::System.EventHandler (this.OnFromInputLabelChanged);
		this.ConvertButton.Clicked += new global::System.EventHandler (this.OnConverButtonClicked);
	}
}
